module7-task1
htmlacademy-javascript/584557-keksobooking-27 pull request #5
Opened 2022-10-11 18:13 UTC by z0rig

2022-10-11 19:24 UTC, frontstall requested changes

2022-10-11 19:24 UTC, frontstall commented on js/data.js
> +      avatar: `img/avatars/user${String(++i).padStart(2, '0')}.png`,
зря исправил, было нагляднее. Чем проще код, тем лучше.

2022-10-11 19:24 UTC, frontstall commented on js/main.js
> +mapCanvasEl.append(createAdEl(getRandomAds()[0]));
https://ru.hexlet.io/blog/posts/sovershennyy-kod-zlye-odnostrochniki

2022-10-11 19:24 UTC, frontstall commented on js/markup.js
> +const popupTemplateEl = document.querySelector('#card').content;
избегай сокращений, есть критерий про это

2022-10-11 19:24 UTC, frontstall commented on js/markup.js
> +    textContent = `${rooms} ${declOfNum(rooms, ['комната', 'комнаты', 'комнат'])}, для ${guests} ${declOfNum(guests, ['гостя', 'гостей', 'гостей'])}`;
declOfNum надо бы называть понятно, без сокращений

2022-10-11 19:24 UTC, frontstall commented on js/markup.js
> +  } else {
вложенные if-ы неудобно читать. Тем более, тут можно отрефакторить на ранний возврат:

```js
if (rooms && guests) {
  return someResult;
}

if (rooms) {
  return anotherResult;
}

if (guests) {
  return oneMoreResult;
}
```

2022-10-11 19:24 UTC, frontstall commented on js/markup.js
> +  } else {
аналогично

2022-10-11 19:24 UTC, frontstall commented on js/markup.js
> +const addDataToAdEl = (adEl, dataMap) => {
очень сложная функция с не совсем понятной абстракцией. Называется `add`, но может и удалять, это странно. Выглядит, как будто можно обойтись без неё

2022-10-11 19:24 UTC, frontstall commented on js/markup.js
> +  const dataMap = {
круто, что так умеешь, но тут нужен максимально тупой код: проверил наличие данных, если есть – нашёл подходящий элемент, записал в него данные. Проблема этого кода в том, что любое изменение (например, нужно кроме текста, записывать ещё какой-нибудь атрибут, aria или alt или что угодно) в нём уже всё сломает.

2022-10-11 19:24 UTC, frontstall commented on js/util.js
> +function getRandomPositiveInteger (a, b) {
стрелочные функции, есть критерий про это

2022-10-12 00:23 UTC, z0rig commented on js/markup.js
> +  const dataMap = {
я так и написа сначала, но получилось просто портянка однотипных if else, где в if проверяется наличие данных(если они есть - добавляем их в разметку), а в else везде один и тот же метод удаления элемента(если данных нет)
подскажи как лучше будет все-таки

2022-10-13 19:30 UTC, merged